services:
  db:
    image: postgres:latest
    container_name: postgres-database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
        #   - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:${POSTGRES_PORT}"

  web:
    build: backend/.
    container_name: backend-app
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8999:80"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

# volumes:
#   postgres_data:
#     driver: local
