version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres-database
    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:${POSTGRES_PORT}"

  web:
    build: backend/.
    container_name: backend-app
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
    driver: local
