FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y gcc

RUN pip install --upgrade pip && pip install poetry

COPY pyproject.toml poetry.lock* ./

RUN poetry config virtualenvs.create false 

RUN poetry install --no-interaction --no-ansi --no-root

COPY . .

EXPOSE 5000

CMD ["bash", "-c", "python manage.py migrate && exec gunicorn blogapi.wsgi:application --bind 0.0.0.0:5000"]
