
run:
    poetry run python manage.py runserver 7000

makemigrations:
    poetry run python manage.py makemigrations

migrate:
    poetry run python manage.py migrate

superuser:
    poetry run python manage.py createsuperuser

shell:
    poetry run python manage.py shell

test:
    poetry run python manage.py test

test-unit:
    poetry run python manage.py test blog/tests/unit

test-integration:
    poetry run python manage.py test blog/tests/integration

test-api:
    poetry run python manage.py test blog/tests/api
